### ISSUE TITLE
As a user, I should be able to view a list of vendor items I am able to request a quote with.

### ISSUE THREAD

**Issue by 123callumb** [123callumb/case-studies-basic-implementation#13]
- [x] Setup HTML/CSS
- [x] Add JS Search
- [x] Add manager for and methods getting all vendor items
- [x] Load vendor item data into razor page
- [x] Create feature branch

**Comment by HarriFent** [comment]
https://github.com/123callumb/case-studies-basic-implementation/commit/121b5afaabc8fea43434b464ca4d80cbea896b0c
