### ISSUE TITLE
As a vendor, my home page should contain a list of all of the quotes requested for the vendor i work for.

### ISSUE THREAD

**Issue by 123callumb** [123callumb/case-studies-basic-implementation#23]
- [x] Create a bunch of fake quotes
- [x] Manager for getting quotes and method for quotes just for the vendor
- [x] Make it look like other designs
- [x] Create feature branch

**Comment by HarriFent** [comment]
https://github.com/123callumb/case-studies-basic-implementation/commit/5bbc2e4d3905495b974c88621b72c14fd192a1f0
