### ISSUE TITLE
As a user, there should be a modal window for showing a list of quote responses where the user can approve or reject the latest one.

### ISSUE THREAD

**Issue by 123callumb** [123callumb/case-studies-basic-implementation#29]
- [x] List of quote responses for given quote
- [x] Ability to reject the latest response 
- [x] Ability to accept the latest response 
- [x] Accepting and rejecting the responses changes the status of them in the database.
- [x] Add tingle js for the modal
- [x] Replace the JQuery <3

**Comment by HarriFent** [comment]
https://github.com/123callumb/case-studies-basic-implementation/commit/e63be1c96d932f6fdf690313cb678ba0ad4c63da
